# Generated by Django 5.1.4 on 2024-12-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('В работе', 'В работе'), ('Завершён', 'Завершён'), ('Отменён', 'Отменён')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('Вошел', 'Вошел'), ('Вышел', 'Вышел'), ('Создал', 'Создал'), ('Обновил', 'Обновил'), ('Удалил', 'Удалил')], max_length=10),
        ),
    ]
